# Generated by Django 2.1.4 on 2020-07-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=1000, verbose_name='功能')),
                ('command', models.CharField(max_length=500, verbose_name='命令')),
            ],
            options={
                'verbose_name': 'git版本管理',
                'db_table': 'gitversion',
            },
        ),
    ]
