# Generated by Django 2.1.4 on 2020-07-06 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitVersionManagement', '0002_gitversion_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='gitversion',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gitVersionManagement.GitCategory'),
        ),
    ]
