# Generated by Django 2.1.4 on 2020-07-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitVersionManagement', '0003_auto_20200706_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitcategory',
            options={'verbose_name': '类别'},
        ),
        migrations.AlterModelTable(
            name='gitcategory',
            table='gitcategory',
        ),
    ]
