# Generated by Django 2.1.4 on 2020-07-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitVersionManagement', '0004_auto_20200706_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcategory',
            name='category',
            field=models.CharField(max_length=40, verbose_name='类别'),
        ),
    ]
